#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH

set -o errexit
set -o xtrace


ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources
echo "[debug] ROOT_DIR $ROOT_DIR"

if [ ! -d "${ROOT_DIR}" ]; then
    mkdir -p ${ROOT_DIR}
    echo "[debug] create $ROOT_DIR"
fi

# ==================== pxc_scheduler_handler ====================

SCHEDULER_ROOT_DIR="${ROOT_DIR}/pxc_scheduler_handler"

sudo rm -rf ${SCHEDULER_ROOT_DIR}

git clone "${GIT_REPO:-https://github.com/Tusamarco/pxc_scheduler_handler}" "${SCHEDULER_ROOT_DIR}"

pushd $SCHEDULER_ROOT_DIR
    if [ -n "${GIT_REPO}" ]; then
        git remote set-url origin "${GIT_REPO}"
        git fetch --all
    fi

    git reset --hard
    git clean -xdf

    mkdir ./target

    echo "[debug] Branch $BRANCH"

    if [ -n "${BRANCH}" ]; then
        git checkout "${BRANCH}"
    fi
    if [ -n "${GIT_REPO}" -a -n "${BRANCH}" ]; then
        git pull origin ${BRANCH}
    fi
popd
